name: Github Actions
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        nim-version: ['1.6.8', '1.6.x']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-version }}
    - run: nimble install -y
    - run: nimble install -y ws
    - run: nim c -r tests/test.nim
    - run: nim c -r tests/test_http.nim
    - run: nim c -r tests/test_websockets.nim
